[[courses]]
course_code = "22MX44001"
credit = 0.0
assessment_method = "考查"
course_name = "劳动教育概论"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 8

[courses.hours]
theory = 8
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP2030"
credit = 4.0
assessment_method = "考查"
course_name = "离散数学"
recommended_year_semester = "第二学年秋季"
track = "计算机轨道（计划修读计算机专业选择此轨道内课程）"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "COMP2053"
credit = 3.5
assessment_method = "考试"
course_name = "数字逻辑设计"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算机科学与技术学院"
total_hours = 56

[courses.hours]
theory = 36
lab = 20
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "EE1018"
credit = 4.0
assessment_method = "考查"
course_name = "电路与电子学I"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "机器人与先进制造学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ELPA2003"
credit = 1.0
assessment_method = "考查"
course_name = "先进封装技术概论"
recommended_year_semester = "第二学年秋季"
track = "电封轨道（计划修读电封专业选择此轨道内课程"
course_nature = "必修"
course_category = "其他"
offering_college = "集成电路学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "GEIP1011"
credit = 3.0
assessment_method = "考试"
course_name = "马克思主义基本原理"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "ICDS3024"
credit = 3.0
assessment_method = "考查"
course_name = "半导体器件物理"
recommended_year_semester = "第二学年秋季"
track = "集成轨道（计划修读集成专业选择此轨道内课程）"
course_nature = "必修"
course_category = "其他"
offering_college = "集成电路学院"
total_hours = 48

[courses.hours]
theory = 36
lab = 12
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1004"
credit = 3.0
assessment_method = "考试"
course_name = "概率论与数理统计"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH1005"
credit = 2.0
assessment_method = "考查"
course_name = "复变函数与积分变换"
recommended_year_semester = "第二学年秋季"
track = "通信轨道（计划修读通信专业选择此轨道内课程）,光电轨道（计划修读光电专业选择此轨道内课程）,大数据轨道（计划修读大数据专业选择此轨道内课程）"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH2010"
credit = 2.0
assessment_method = "考查"
course_name = "最优化方法"
recommended_year_semester = "第二学年秋季"
track = "通信轨道（计划修读通信专业选择此轨道内课程）,光电轨道（计划修读光电专业选择此轨道内课程）"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 32

[courses.hours]
theory = 32
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MATH2011"
credit = 3.0
assessment_method = "考查"
course_name = "高等代数"
recommended_year_semester = "第二学年秋季"
track = "大数据轨道（计划修读大数据专业选择此轨道内课程）"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 48

[courses.hours]
theory = 40
lab = 8
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "MSE3002"
credit = 3.0
assessment_method = "考查"
course_name = "半导体物理与器件"
recommended_year_semester = "第二学年秋季"
track = "电封轨道（计划修读电封专业选择此轨道内课程"
course_nature = "必修"
course_category = "其他"
offering_college = "材料科学与工程学院"
total_hours = 48

[courses.hours]
theory = 48
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PE1002C"
credit = 0.5
assessment_method = "考查"
course_name = "体育C"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "人文与社会科学学院"
total_hours = 16

[courses.hours]
theory = 16
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 16
[[courses]]
course_code = "PHYS1004"
credit = 1.0
assessment_method = "考查"
course_name = "大学物理实验II"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 24

[courses.hours]
theory = 2
lab = 22
practice = 0
exercise = 0
computer = 0
tutoring = 0
[[courses]]
course_code = "PHYS1005B"
credit = 4.0
assessment_method = "考试"
course_name = "大学物理XB"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "理学院"
total_hours = 64

[courses.hours]
theory = 64
lab = 0
practice = 0
exercise = 0
computer = 0
tutoring = 0
